server:
  port: 8766
spring:
  application:
    name: eureka-ribbon-hystrix-client
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: localhost
    home-page-url:  https://${eureka.instance.hostname}:${server.port}/
#    status-page-url: http://${eureka.instance.hostname}:${server.port}${management.context-path}/info
    # 配置健康监控页面
#    health-check-url: http://${eureka.instance.hostname}:${server.port}${management.context-path}/health
    # 设置Instance ID
    #instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 续约的时间间隔，默认为30s,不建议修改
    #lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    region: ch-east-1
# 监控配置
management:
  security:
    enabled: false
#  port: ${server.port}
#  context-path: /moniter
endpoints:
  enabled: true
  shutdown:
    enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}