server:
  port: 8767
spring:
  application:
    name: eureka-feign-hysrix-client
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    region: ch-east-1
    healthcheck:
      enabled: true
# 监控配置
management:
  security:
    enabled: false
endpoints:
  enabled: true
  shutdown:
    enabled: false
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    head: ${spring.application.name}
    body: Welcome, this is ${spring.application.name} @ ${server.port}
feign:
  hystrix:
    enabled: true