spring:
  application:
    name: jwt-auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_jwt?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 9200
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
