spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
