spring:
  application:
    name: service-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.190:3306/oauth2?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 5000
#  context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
