eureka:
  instance:
    hostname: localhost
    # 续约的时间间隔，默认为30s,不建议修改
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    region: ch-east-1
spring:
  application:
    name: mysql-zipkin-server
  datasource:
    url: jdbc:mysql://192.168.31.96:3306/sleuth?useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 9411
zipkin:
  storage:
    type: mysql